In [27]:
import pandas as pd

In [28]:
dataset_path = '/Users/mocatfrio/Scripts/kmppd/system/database/covtype.csv'

In [29]:
df = pd.read_csv(dataset_path)
df

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40,Cover_Type
0,2596,51,3,258,0,510,221,232,148,6279,...,0,0,0,0,0,0,0,0,0,5
1,2590,56,2,212,-6,390,220,235,151,6225,...,0,0,0,0,0,0,0,0,0,5
2,2804,139,9,268,65,3180,234,238,135,6121,...,0,0,0,0,0,0,0,0,0,2
3,2785,155,18,242,118,3090,238,238,122,6211,...,0,0,0,0,0,0,0,0,0,2
4,2595,45,2,153,-1,391,220,234,150,6172,...,0,0,0,0,0,0,0,0,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
581007,2396,153,20,85,17,108,240,237,118,837,...,0,0,0,0,0,0,0,0,0,3
581008,2391,152,19,67,12,95,240,237,119,845,...,0,0,0,0,0,0,0,0,0,3
581009,2386,159,17,60,7,90,236,241,130,854,...,0,0,0,0,0,0,0,0,0,3
581010,2384,170,15,60,5,90,230,245,143,864,...,0,0,0,0,0,0,0,0,0,3
581011,2383,165,13,60,4,67,231,244,141,875,...,0,0,0,0,0,0,0,0,0,3

In [30]:
# normalized
for col in df.columns:
        normalized_value = (df[col] - df[col].min()) / (df[col].max() - df[col].min())
#         normalized_value = df[col] / df[col].max()
#         normalized_value = (df[col] - df[col].mean()) / df[col].std()
        df[col] = normalized_value
        
df.head()

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40,Cover_Type
0,0.368684,0.141667,0.045455,0.184681,0.223514,0.071659,0.870079,0.913386,0.582677,0.875366,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.666667
1,0.365683,0.155556,0.030303,0.151754,0.215762,0.054798,0.866142,0.925197,0.594488,0.867838,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.666667
2,0.472736,0.386111,0.136364,0.191840,0.307494,0.446817,0.921260,0.937008,0.531496,0.853339,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.166667
3,0.463232,0.430556,0.272727,0.173228,0.375969,0.434172,0.937008,0.937008,0.480315,0.865886,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.166667
4,0.368184,0.125000,0.030303,0.109520,0.222222,0.054939,0.866142,0.921260,0.590551,0.860449,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.666667

In [31]:
# get 10 first columns 
df.drop([col for col in df.columns[10:]], axis=1, inplace=True)
df

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points
0,0.368684,0.141667,0.045455,0.184681,0.223514,0.071659,0.870079,0.913386,0.582677,0.875366
1,0.365683,0.155556,0.030303,0.151754,0.215762,0.054798,0.866142,0.925197,0.594488,0.867838
2,0.472736,0.386111,0.136364,0.191840,0.307494,0.446817,0.921260,0.937008,0.531496,0.853339
3,0.463232,0.430556,0.272727,0.173228,0.375969,0.434172,0.937008,0.937008,0.480315,0.865886
4,0.368184,0.125000,0.030303,0.109520,0.222222,0.054939,0.866142,0.921260,0.590551,0.860449
...,...,...,...,...,...,...,...,...,...,...
581007,0.268634,0.425000,0.303030,0.060845,0.245478,0.015175,0.944882,0.933071,0.464567,0.116688
581008,0.266133,0.422222,0.287879,0.047960,0.239018,0.013348,0.944882,0.933071,0.468504,0.117803
581009,0.263632,0.441667,0.257576,0.042949,0.232558,0.012646,0.929134,0.948819,0.511811,0.119058
581010,0.262631,0.472222,0.227273,0.042949,0.229974,0.012646,0.905512,0.964567,0.562992,0.120452
581011,0.262131,0.458333,0.196970,0.042949,0.228682,0.009414,0.909449,0.960630,0.555118,0.121985

In [32]:
# insert label 
label = 'Customer'
df.insert(0, "label", [label + "-" + str(i+1) for i in range(len(df))], True)
df

,label,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points
0,Customer-1,0.368684,0.141667,0.045455,0.184681,0.223514,0.071659,0.870079,0.913386,0.582677,0.875366
1,Customer-2,0.365683,0.155556,0.030303,0.151754,0.215762,0.054798,0.866142,0.925197,0.594488,0.867838
2,Customer-3,0.472736,0.386111,0.136364,0.191840,0.307494,0.446817,0.921260,0.937008,0.531496,0.853339
3,Customer-4,0.463232,0.430556,0.272727,0.173228,0.375969,0.434172,0.937008,0.937008,0.480315,0.865886
4,Customer-5,0.368184,0.125000,0.030303,0.109520,0.222222,0.054939,0.866142,0.921260,0.590551,0.860449
...,...,...,...,...,...,...,...,...,...,...,...
581007,Customer-581008,0.268634,0.425000,0.303030,0.060845,0.245478,0.015175,0.944882,0.933071,0.464567,0.116688
581008,Customer-581009,0.266133,0.422222,0.287879,0.047960,0.239018,0.013348,0.944882,0.933071,0.468504,0.117803
581009,Customer-581010,0.263632,0.441667,0.257576,0.042949,0.232558,0.012646,0.929134,0.948819,0.511811,0.119058
581010,Customer-581011,0.262631,0.472222,0.227273,0.042949,0.229974,0.012646,0.905512,0.964567,0.562992,0.120452
581011,Customer-581012,0.262131,0.458333,0.196970,0.042949,0.228682,0.009414,0.909449,0.960630,0.555118,0.121985

In [33]:
# reset index 
df = df.reset_index(drop=True)
df.insert(0, "id", [i + 1 for i in df.index], True)
df

,id,label,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points
0,1,Customer-1,0.368684,0.141667,0.045455,0.184681,0.223514,0.071659,0.870079,0.913386,0.582677,0.875366
1,2,Customer-2,0.365683,0.155556,0.030303,0.151754,0.215762,0.054798,0.866142,0.925197,0.594488,0.867838
2,3,Customer-3,0.472736,0.386111,0.136364,0.191840,0.307494,0.446817,0.921260,0.937008,0.531496,0.853339
3,4,Customer-4,0.463232,0.430556,0.272727,0.173228,0.375969,0.434172,0.937008,0.937008,0.480315,0.865886
4,5,Customer-5,0.368184,0.125000,0.030303,0.109520,0.222222,0.054939,0.866142,0.921260,0.590551,0.860449
...,...,...,...,...,...,...,...,...,...,...,...,...
581007,581008,Customer-581008,0.268634,0.425000,0.303030,0.060845,0.245478,0.015175,0.944882,0.933071,0.464567,0.116688
581008,581009,Customer-581009,0.266133,0.422222,0.287879,0.047960,0.239018,0.013348,0.944882,0.933071,0.468504,0.117803
581009,581010,Customer-581010,0.263632,0.441667,0.257576,0.042949,0.232558,0.012646,0.929134,0.948819,0.511811,0.119058
581010,581011,Customer-581011,0.262631,0.472222,0.227273,0.042949,0.229974,0.012646,0.905512,0.964567,0.562992,0.120452
581011,581012,Customer-581012,0.262131,0.458333,0.196970,0.042949,0.228682,0.009414,0.909449,0.960630,0.555118,0.121985

In [34]:
def get_range_row(max_val, data_num):
    start_row = randomize(max_val=max_val)
    end_row = start_row + data_num
    if end_row > max_val:
        start_row, end_row = get_range_row(max_val, data_num)
    return start_row, end_row

In [47]:
import random


def randomize(min_val=0, max_val=None):
    if not max_val:
        max_val = MAX_VALUE
    if min_val > max_val:
        min_val = max_val
    range_start = random.randint(min_val, max_val) 
    range_end = range_start + random.randint(min_val, round(max_val/2))
    return random.randint(range_start, range_end)

def get_col_index(min_val, max_val, last_index):
    idx = randomize(min_val, max_val)
    if idx == last_index:
        idx = get_col_index(min_val, max_val, last_index)
    return idx

In [58]:
# get row based on required data and dim size 
data_num = 500
dim_size = 2

start_row, end_row = get_range_row(len(df), data_num)

result = [df.iloc[start_row:end_row, 0:2]]
last_dim = None
for d in range(dim_size): 
    dim = get_col_index(2, len(df.columns)-1, last_dim)
    last_dim = dim
    result.append(df.iloc[start_row:end_row, dim])
    
res = pd.concat(result, axis=1)


# df = df.iloc[start_row:end_row, :dim_size + 2]
res

            id            label  Hillshade_3pm  Elevation
432684  432685  Customer-432685       0.519685   0.552276
432685  432686  Customer-432686       0.515748   0.549775
432686  432687  Customer-432687       0.547244   0.548774
432687  432688  Customer-432688       0.555118   0.547774
432688  432689  Customer-432689       0.555118   0.546773
...        ...              ...            ...        ...
433179  433180  Customer-433180       0.767717   0.541271
433180  433181  Customer-433181       0.696850   0.544272
433181  433182  Customer-433182       0.637795   0.545773
433182  433183  Customer-433183       0.598425   0.547274
433183  433184  Customer-433184       0.598425   0.546773

[500 rows x 4 columns]

,id,label,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points
0,1,Customer-1,0.368684,0.141667,0.045455,0.184681,0.223514,0.071659,0.870079,0.913386,0.582677,0.875366
1,2,Customer-2,0.365683,0.155556,0.030303,0.151754,0.215762,0.054798,0.866142,0.925197,0.594488,0.867838
2,3,Customer-3,0.472736,0.386111,0.136364,0.191840,0.307494,0.446817,0.921260,0.937008,0.531496,0.853339
3,4,Customer-4,0.463232,0.430556,0.272727,0.173228,0.375969,0.434172,0.937008,0.937008,0.480315,0.865886
4,5,Customer-5,0.368184,0.125000,0.030303,0.109520,0.222222,0.054939,0.866142,0.921260,0.590551,0.860449
...,...,...,...,...,...,...,...,...,...,...,...,...
581007,581008,Customer-581008,0.268634,0.425000,0.303030,0.060845,0.245478,0.015175,0.944882,0.933071,0.464567,0.116688
581008,581009,Customer-581009,0.266133,0.422222,0.287879,0.047960,0.239018,0.013348,0.944882,0.933071,0.468504,0.117803
581009,581010,Customer-581010,0.263632,0.441667,0.257576,0.042949,0.232558,0.012646,0.929134,0.948819,0.511811,0.119058
581010,581011,Customer-581011,0.262631,0.472222,0.227273,0.042949,0.229974,0.012646,0.905512,0.964567,0.562992,0.120452
581011,581012,Customer-581012,0.262131,0.458333,0.196970,0.042949,0.228682,0.009414,0.909449,0.960630,0.555118,0.121985

In [59]:
df.iloc[start_row:end_row, 'Elevation']

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types